# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fedora-custombuild
description: "My personal Aurora DX KDE image"

# CRITICAL FIX: 'latest' ensures you are on the supported Fedora version (likely 43 in Dec 2025)
base-image: ghcr.io/ublue-os/aurora-dx
image-version: latest

modules:
  # 1. System Files (Copies your custom configs)
  - type: files
    files:
      - source: system
        destination: /

  # 2. Package Management (The Modern Way)
  - type: dnf
    repos:
      # Adding the Starship COPR (if you prefer this over the default)
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
        # Note: 'code' (VS Code) is ALREADY in aurora-dx, so we don't list it here.
    remove:
      packages:
        - firefox
        - firefox-langpacks 

  # 3. Flatpaks (Cleaned up for clarity)
  - type: default-flatpaks
    configurations:
      # System-wide Flatpaks (Pre-installed for all users)
      - scope: system
        notify: true
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      
      # Ensure the user repo is explicitly enabled for your own installs later
      - scope: user
        notify: false

  # 4. Signing (Required for GitHub Actions to work)
  - type: signing
